//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_pratique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oeuvre
    {
        public string IdOeuvre { get; set; }
        public string Titre { get; set; }
        public Nullable<decimal> Valeur { get; set; }
        public string IdArtiste { get; set; }
        public string Etat { get; set; }
    
        public virtual Artiste Artiste { get; set; }
    }
}
